apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: ruby-app
    app.kubernetes.io/component: ruby-app
    app.kubernetes.io/instance: ruby-app
    app.kubernetes.io/name: ruby-app
    app.kubernetes.io/part-of: ruby-app
  name: ruby-app
spec:
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ruby-app
    weight: 100
  wildcardPolicy: None
