apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ruby-app
    app.kubernetes.io/component: ruby-app
    app.kubernetes.io/instance: ruby-app
    app.kubernetes.io/name: ruby-app
    app.kubernetes.io/part-of: ruby-app
  name: ruby-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ruby-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ruby-app
        deploymentconfig: ruby-app
    spec:
      containers:
        image: quay.io/paulo_luizetto/ruby-hello-world-image/rhw:v1.0
        imagePullPolicy: Always
        name: ruby-app
        resources:
          limits:
            cpu: 50m
            memory: 150Mi
          requests:
            cpu: 20m
            memory: 75Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
