---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: ruby-app-latest
  namespace: pardini03
spec:
  type: GitHub
  pathname: https://github.com/pluizetto/redhat-acm-app 
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: ruby-app
  namespace: pardini03
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - ruby-app
