apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: prd-clusters 
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      environment: prd 
